project:
  type: website

website:
  title: "Global Commodity Trade Statistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: gct.qmd
        text: Models
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: true
    highlight-style: github
       


