project:
  type: website

website:
  title: "Global Commodity Trade Statistics"
  navbar:
    logo: https://sdmntprsouthcentralus.oaiusercontent.com/files/00000000-4e94-61f7-9546-49c3539bd90c/raw?se=2025-08-02T19%3A15%3A32Z&sp=r&sv=2024-08-04&sr=b&scid=076bc206-6b8b-5dbf-8d0e-586de2cd740c&skoid=a3412ad4-1a13-47ce-91a5-c07730964f35&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-08-01T20%3A15%3A04Z&ske=2025-08-02T20%3A15%3A04Z&sks=b&skv=2024-08-04&sig=IduVxZo7Sd7CD/KjPCA4B9FTi5%2BRmzZABSKbD8ICxho%3D
    left:
      - href: index.qmd
        text: Home
      - href: gct.qmd
        text: Models
      - href: plots.qmd
        text: Plots
      - href: map.qmd
        text: Map
      - href: sources.qmd
        text: Sources
      - href: about.qmd
        text: About
      
     
      
     

format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: true
    highlight-style: github
    
       


